<?php

/**
 * Implements hook_menu().
 */
function islandora_gsearch_index_menu() {
  $items = array();


  $items['admin/islandora/islandora-gsearch-index'] = array(
    'title' => 'Islandora GSearch Index',
    'description' => 'Islandora GSearch Index Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_gsearch_index_configuration'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_islandora_object_ingested().
 */
function islandora_gsearch_index_islandora_object_ingested(AbstractObject $object) {
  if (variable_get('islandora_gsearch_index_fedoragsearch_uri', '')) {
    if (drupal_strtolower($object->state) == 'a') {
      $uri = variable_get('islandora_gsearch_index_fedoragsearch_uri', '');
      $uri .= "/rest?operation=updateIndex&action=fromPid&value={$object->id}";
      file_get_contents($uri);
    } else {
      islandora_gsearch_index_islandora_object_purged($object->id);
    }
  }
}

/**
 * Implements hook_islandora_object_purged().
 */
function islandora_gsearch_index_islandora_object_purged($pid) {
  if (variable_get('islandora_gsearch_index_fedoragsearch_uri', '')) {
    $uri = variable_get('islandora_gsearch_index_fedoragsearch_uri', '');
    $uri .= "/rest?operation=updateIndex&action=deletePid&value={$pid}";
    file_get_contents($uri);
  }
}

/**
 * Implements hook_islandora_object_modified().
 */
function islandora_gsearch_index_islandora_object_modified(AbstractObject $object) {
  islandora_gsearch_index_islandora_object_ingested($object);
}

/**
 * Implements hook_islandora_datastream_ingested().
 */
function islandora_gsearch_index_islandora_datastream_ingested(AbstractObject $object, AbstractDatastream $datastream) {
  islandora_gsearch_index_islandora_object_ingested($object);
}

/**
 * Implements hook_islandora_datastream_modified().
 */
function islandora_gsearch_index_islandora_datastream_modified(AbstractObject $object, AbstractDatastream $datastream) {
  islandora_gsearch_index_islandora_object_ingested($object);
}

/**
 * Implements hook_islandora_datastream_purged().
 */
function islandora_gsearch_index_islandora_datastream_purged(AbstractObject $object, $dsid) {
  islandora_gsearch_index_islandora_object_ingested($object);
}
